export const WEATHER_FETCH = "WEATHER_FETCH";
export const WEATHER_FETCH_SUCCESS = "WEATHER_FETCH_SUCCESS";
export const WEATHER_FETCH_START = "WEATHER_FETCH_START";
export const WEATHER_FETCH_FAIL = "WEATHER_FETCH_FAIL";


export const UPDATE_SELECTED_CITY = "UPDATE_SELECTED_CITY";

